# ==============================
# 🖥️  Monitor Configuration (v2)
# ==============================

# Main monitor — LG Ultragear (DP-3, 144 Hz, on the LEFT)
monitorv2 {
  output = DP-3
  mode = 2560x1440@144
  position = 0x0
  scale = 1
  transform = 0
  workspace = 1
}

# Secondary monitor — Acer SA272U E (HDMI-A-1, 60 Hz, on the RIGHT)
monitorv2 {
  output = HDMI-A-1
  mode = 2560x1440@100
  position = 2560x0
  scale = 1
  transform = 0
  workspace = 9
}


workspace = 1, monitor:DP-3, persistent:true, default:true
workspace = 2, monitor:DP-3, persistent:true
workspace = 3, monitor:DP-3, persistent:true
workspace = 4, monitor:DP-3, persistent:true
workspace = 5, monitor:DP-3, persistent:true


workspace = 6, monitor:HDMI-A-1, persistent:true
workspace = 7, monitor:HDMI-A-1, persistent:true
workspace = 8, monitor:HDMI-A-1, persistent:true
workspace = 9, monitor:HDMI-A-1, persistent:true
workspace = 10, monitor:HDMI-A-1, persistent:true, default:true
