# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #9E9E9E

background #000000
foreground #ECECEC

color0 #000000
color1 #603F3F
color2 #784E4E
color3 #7A5050
color4 #865757
color5 #A46B6B
color6 #C88282
color7 #DBDBDB
color8 #999999
color9 #603F3F
color10 #784E4E
color11 #7A5050
color12 #865757
color13 #A46B6B
color14 #C88282
color15 #DBDBDB

mark1_foreground #C86868
mark2_foreground #DBAFAF
mark3_foreground #C86868

