# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #BDB49E

background #1A1A1C
foreground #F6E9D1

color0 #454548
color1 #538863
color2 #8B7C4B
color3 #588B49
color4 #67AF80
color5 #B4BC4E
color6 #E5B250
color7 #EAD8B5
color8 #A3977E
color9 #538863
color10 #8B7C4B
color11 #588B49
color12 #67AF80
color13 #B4BC4E
color14 #E5B250
color15 #EAD8B5

mark1_foreground #E5AD40
mark2_foreground #EACC91
mark3_foreground #E5AD40

