# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #8E9E92

background #161514
foreground #EAECE0

color0 #41403D
color1 #51482A
color2 #3F7762
color3 #738729
color4 #46874D
color5 #75A30E
color6 #B6C96D
color7 #D8DCCB
color8 #979A8E
color9 #51482A
color10 #3F7762
color11 #738729
color12 #46874D
color13 #75A30E
color14 #B6C96D
color15 #D8DCCB

mark1_foreground #B1C957
mark2_foreground #CEDCA2
mark3_foreground #B1C957

